version: '3.0'
services:
  pgsql:
    image: postgres:14.6-alpine
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    volumes:
      - mongodata:/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - redis_data:/data
    environment:
      PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    env_file:
      - ./.env

  neo4j:
    image: neo4j:5.14
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data/
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-neo4jpass}


  bot:
    build: .
    restart: always
    depends_on:
      - pgsql
      - mongodb
      - redis
      - neo4j
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodata:
    driver: local
  redis_data:
  neo4j_data: