version: '3.0'
services:
  postgres:
    image: postgres:14.6-alpine
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    env_file:
      - ./.env

  mongodb:
    image: mongo:7.0
    ports:
      - 27017:27017
    env_file:
      - ./.env
    volumes:
      - mongodata:/data

  redis:
    image: redis:7.2-alpine
    volumes:
      - redis_data:/data

    env_file:
      - ./.env

  bot:
    build: .
    restart: always
    depends_on:
      - postgres
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodata:
    driver: local
  redis_data: